export const SET_PLAYER = 'SET_PLAYER';
export const CLEAR_PLAYER = 'CLEAR_PLAYER';

export const GET_PLAYER_REQUEST = 'GET_PLAYER_REQUEST';
export const GET_PLAYER_SUCCESS = 'GET_PLAYER_SUCCESS';
export const GET_PLAYER_FAILURE = 'GET_PLAYER_FAILURE';

export const GET_MATCHES_LIST_REQUEST = 'GET_MATCHES_LIST_REQUEST';
export const GET_MATCHES_LIST_SUCCESS = 'GET_MATCHES_LIST_SUCCESS';
export const GET_MATCHES_LIST_FAILURE = 'GET_MATCHES_LIST_FAILURE';

export const GET_PLAYER_STATS = 'GET_PLAYER_STATS';

export const GET_GLOBAL_STATS_REQUEST = 'GET_GLOBAL_STATS_REQUEST';
export const GET_GLOBAL_STATS_SUCCESS = 'GET_GLOBAL_STATS_SUCCESS';
export const GET_GLOBAL_STATS_FAILURE = 'GET_GLOBAL_STATS_FAILURE';
